apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  username: bXlzcWw=
  password: ZXN1bkAxMzEz
  rootPassword: ZXN1bkAxMzEz
  database: bXlzcWw=
  db-password: ZXN1bkAxMzEz
  auth_key: ZXN1bkAxMzEz
  secure_auth_key: ZXN1bkAxMzEz
  logged_in_key: ZXN1bkAxMzEz
  nonce_key: ZXN1bkAxMzEz
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
        tier: frontend
    spec:
      containers:
      - name: mysql
        image: mysql
        ports:
        - name: mysql-port
          containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: rootPassword
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: database


---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  ports:
  - port: 3306
    protocol: TCP
  selector:
    app: mysql




