apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2021-01-08T02:42:33Z"
  labels:
    key: value
    run: nginx
  name: nginx
  resourceVersion: "178013"
  selfLink: /api/v1/namespaces/user-11/pods/nginx
  uid: 4204d11a-cb0c-4335-9c72-50a6649d7fb2
spec:
  containers:
  - name: nginx        
    image: nginx
    livenessProbe:
      httpGet:
        path: /
        port: 200
    readinessProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 10
    env:
    - name: DUMMY_DATABASE_PASSWORD
      value: "admin"
    imagePullPolicy: Always
    name: nginx
    resources:
      requests:
        memory: "50Mi"
        cpu: "50m"
      limits:
        memory: "100Mi"
        cpu: "100m"
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - name: htmldir
      mountPath: /usr/share/nginx/html/ 
      readOnly: true
  - name: busybox
    image: busybox
    command: ["/bin/sh","-c","--"]
    args: ["while true; do echo 'admin' >> /html/index.html && sleep 5; done;"]
    volumeMounts:
    - name: htmldir
      mountPath: /html
  volumes: 
    - name: htmldir
      emptyDir: {}

